version: '3'
services:
  fuseki1:
    image: stain/jena-fuseki
    container_name: fuseki1
    ports:
      - "3030:3030"
    volumes:
      - ./data1/config.ttl:/fuseki/config.ttl
      - ./data1:/staging  # Mount data1 directory as /staging
      - ./entrypoint.sh:/entrypoint.sh
    command: ["/entrypoint.sh"]
    environment:
      - ADMIN_PASSWORD=admin

  fuseki2:
    image: stain/jena-fuseki
    container_name: fuseki2
    ports:
      - "3031:3030"
    volumes:
      - ./data2/config.ttl:/fuseki/config.ttl
      - ./data2:/staging  # Mount data2 directory as /staging
      - ./entrypoint.sh:/entrypoint.sh
    command: ["/entrypoint.sh"]
    environment:
      - ADMIN_PASSWORD=admin